const PERSONALITY_LOOKBACK_DAYS = 14;

// Personality templates are scored against real behavior metrics.
const PET_PERSONALITY_DEFINITIONS = [
    {
        id: 'dawn_guardian',
        emoji: '🌅',
        name: 'Hộ Vệ Bình Minh',
        description: 'Luôn chăm pet đều đặn và giữ nhịp yêu thương ổn định.',
        weights: { consistency: 0.24, teamwork: 0.2, vitality: 0.18, nurturing: 0.12, balance: 0.16, devotion: 0.1 },
        skill: {
            id: 'sunrise_pulse',
            name: 'Nhịp Bình Minh',
            description: 'Khi cho ăn hoặc vuốt ve: +4 Health, +6 Mood, +4 XP, +2 Coins.',
            triggerActions: ['feed', 'pet'],
            cooldownMinutes: 120,
            bonusStats: { health: 4, mood: 6 },
            bonusXp: 4,
            bonusCoins: 2,
        },
    },
    {
        id: 'moon_whisperer',
        emoji: '🌙',
        name: 'Kẻ Thì Thầm Ánh Trăng',
        description: 'Ấm áp, dịu dàng, giúp pet thư giãn và vui vẻ hơn.',
        weights: { affection: 0.32, moodCare: 0.2, teamwork: 0.18, consistency: 0.14, balance: 0.16 },
        skill: {
            id: 'moon_hug',
            name: 'Ôm Trăng Dịu',
            description: 'Khi vuốt ve hoặc chơi: +10 Mood, +2 Cleanliness, +3 XP.',
            triggerActions: ['pet', 'play'],
            cooldownMinutes: 105,
            bonusStats: { mood: 10, cleanliness: 2 },
            bonusXp: 3,
            bonusCoins: 1,
        },
    },
    {
        id: 'snack_alchemist',
        emoji: '🍜',
        name: 'Luyện Kim Bếp Nhỏ',
        description: 'Rất quan tâm no bụng và thể lực của pet.',
        weights: { nurturing: 0.42, vitality: 0.2, consistency: 0.16, devotion: 0.12, discipline: 0.1 },
        skill: {
            id: 'warm_bowl',
            name: 'Bát Ấm Đầy',
            description: 'Khi cho ăn: +16 Hunger, +5 Health, +5 XP.',
            triggerActions: ['feed'],
            cooldownMinutes: 95,
            bonusStats: { hunger: 16, health: 5 },
            bonusXp: 5,
            bonusCoins: 1,
        },
    },
    {
        id: 'bubble_priestess',
        emoji: '🫧',
        name: 'Tư Tế Bọt Nước',
        description: 'Ưu tiên sạch sẽ và nhịp chăm sóc tinh tế.',
        weights: { hygiene: 0.45, consistency: 0.2, discipline: 0.16, vitality: 0.1, balance: 0.09 },
        skill: {
            id: 'pure_breeze',
            name: 'Gió Tinh Khiết',
            description: 'Khi tắm: +18 Cleanliness, +4 Mood, +4 XP.',
            triggerActions: ['bathe'],
            cooldownMinutes: 90,
            bonusStats: { cleanliness: 18, mood: 4 },
            bonusXp: 4,
            bonusCoins: 1,
        },
    },
    {
        id: 'joy_sprinter',
        emoji: '🎈',
        name: 'Vận Động Viên Niềm Vui',
        description: 'Pet luôn tràn năng lượng nhờ các hoạt động chơi đùa.',
        weights: { playful: 0.4, vitality: 0.2, consistency: 0.12, teamwork: 0.12, devotion: 0.16 },
        skill: {
            id: 'party_dash',
            name: 'Đà Mở Hội',
            description: 'Khi chơi: +8 Health, +10 Mood, +5 XP, +2 Coins.',
            triggerActions: ['play'],
            cooldownMinutes: 100,
            bonusStats: { health: 8, mood: 10 },
            bonusXp: 5,
            bonusCoins: 2,
        },
    },
    {
        id: 'harmony_weaver',
        emoji: '🧵',
        name: 'Thợ Dệt Hòa Hợp',
        description: 'Cặp đôi phối hợp đều tay và cân bằng cực tốt.',
        weights: { teamwork: 0.32, balance: 0.3, consistency: 0.16, discipline: 0.12, devotion: 0.1 },
        skill: {
            id: 'duet_sync',
            name: 'Đồng Điệu Song Hành',
            description: 'Mọi hành động chăm sóc: +3 tất cả chỉ số, +6 XP, +2 Coins.',
            triggerActions: ['feed', 'pet', 'bathe', 'play'],
            cooldownMinutes: 150,
            bonusStats: { health: 3, mood: 3, hunger: 3, cleanliness: 3 },
            bonusXp: 6,
            bonusCoins: 2,
        },
    },
    {
        id: 'storm_tamer',
        emoji: '⛈️',
        name: 'Ngự Lôi Cảm Xúc',
        description: 'Mạnh mẽ trong giai đoạn pet mệt hoặc tụt chỉ số.',
        requirements: { vitalityMax: 60 },
        weights: { devotion: 0.28, consistency: 0.22, affection: 0.16, nurturing: 0.14, hygiene: 0.1, playful: 0.1 },
        skill: {
            id: 'storm_shield',
            name: 'Lá Chắn Giông Bão',
            description: 'Khi vuốt ve hoặc tắm: +10 Health, +6 Mood, +3 XP.',
            triggerActions: ['pet', 'bathe'],
            cooldownMinutes: 110,
            bonusStats: { health: 10, mood: 6 },
            bonusXp: 3,
            bonusCoins: 1,
        },
    },
    {
        id: 'ember_caregiver',
        emoji: '🔥',
        name: 'Người Giữ Lửa',
        description: 'Nhịp chăm đều, quyết liệt và bền bỉ theo ngày.',
        weights: { devotion: 0.34, consistency: 0.24, vitality: 0.16, discipline: 0.16, teamwork: 0.1 },
        skill: {
            id: 'ember_boost',
            name: 'Lửa Âm Ấm',
            description: 'Khi cho ăn hoặc chơi: +6 Health, +8 Hunger, +4 XP.',
            triggerActions: ['feed', 'play'],
            cooldownMinutes: 125,
            bonusStats: { health: 6, hunger: 8 },
            bonusXp: 4,
            bonusCoins: 1,
        },
    },
    {
        id: 'dew_healer',
        emoji: '🌿',
        name: 'Dược Sư Sương Sớm',
        description: 'Đề cao sự hồi phục bền vững cho pet.',
        weights: { nurturing: 0.3, hygiene: 0.24, vitality: 0.2, consistency: 0.16, affection: 0.1 },
        skill: {
            id: 'herbal_touch',
            name: 'Thảo Mộc Xoa Dịu',
            description: 'Khi tắm hoặc cho ăn: +7 Health, +7 Cleanliness, +4 XP.',
            triggerActions: ['bathe', 'feed'],
            cooldownMinutes: 115,
            bonusStats: { health: 7, cleanliness: 7 },
            bonusXp: 4,
            bonusCoins: 1,
        },
    },
    {
        id: 'starlight_keeper',
        emoji: '✨',
        name: 'Người Canh Sao',
        description: 'Ổn định cảm xúc pet và thường xuyên khám phá.',
        weights: { consistency: 0.2, explorer: 0.26, moodCare: 0.2, teamwork: 0.12, discipline: 0.12, vitality: 0.1 },
        skill: {
            id: 'star_bless',
            name: 'Phúc Quang Tinh Tú',
            description: 'Khi chơi hoặc vuốt ve: +8 Mood, +4 XP, +3 Coins.',
            triggerActions: ['play', 'pet'],
            cooldownMinutes: 130,
            bonusStats: { mood: 8 },
            bonusXp: 4,
            bonusCoins: 3,
        },
    },
    {
        id: 'pathfinder_ranger',
        emoji: '🧭',
        name: 'Hoa Tiêu Viễn Chinh',
        description: 'Yêu thích khám phá và giữ pet sẵn sàng hành trình.',
        weights: { explorer: 0.38, vitality: 0.2, playful: 0.14, consistency: 0.12, discipline: 0.16 },
        skill: {
            id: 'trail_focus',
            name: 'Định Hướng Hành Trình',
            description: 'Khi chơi: +5 Health, +5 Hunger, +5 XP, +2 Coins.',
            triggerActions: ['play'],
            cooldownMinutes: 105,
            bonusStats: { health: 5, hunger: 5 },
            bonusXp: 5,
            bonusCoins: 2,
        },
    },
    {
        id: 'treasure_hunter',
        emoji: '💰',
        name: 'Thợ Săn Kho Báu',
        description: 'Khéo tích lũy tài nguyên và tối ưu hành động.',
        weights: { explorer: 0.24, shopper: 0.26, discipline: 0.2, devotion: 0.14, consistency: 0.16 },
        skill: {
            id: 'coin_surge',
            name: 'Lộc Vàng Đổ Bộ',
            description: 'Mọi hành động chăm sóc: +3 XP, +4 Coins.',
            triggerActions: ['feed', 'pet', 'bathe', 'play'],
            cooldownMinutes: 150,
            bonusStats: {},
            bonusXp: 3,
            bonusCoins: 4,
        },
    },
    {
        id: 'velvet_diplomat',
        emoji: '🎩',
        name: 'Quý Tộc Cân Bằng',
        description: 'Tinh tế, phối hợp tốt và luôn giữ trạng thái hài hòa.',
        weights: { balance: 0.34, teamwork: 0.24, affection: 0.12, discipline: 0.16, vitality: 0.14 },
        skill: {
            id: 'etiquette_grace',
            name: 'Nghi Thức Êm Đềm',
            description: 'Khi vuốt ve: +6 Mood, +4 Cleanliness, +4 XP.',
            triggerActions: ['pet'],
            cooldownMinutes: 90,
            bonusStats: { mood: 6, cleanliness: 4 },
            bonusXp: 4,
            bonusCoins: 2,
        },
    },
    {
        id: 'cloud_dreamer',
        emoji: '☁️',
        name: 'Kẻ Mộng Mây',
        description: 'Lãng mạn, ưu tiên cảm xúc và khoảnh khắc nhẹ nhàng.',
        weights: { affection: 0.34, playful: 0.16, moodCare: 0.22, consistency: 0.12, teamwork: 0.16 },
        skill: {
            id: 'dream_loop',
            name: 'Vòng Mộng Dịu',
            description: 'Khi vuốt ve hoặc chơi: +12 Mood, +2 XP.',
            triggerActions: ['pet', 'play'],
            cooldownMinutes: 95,
            bonusStats: { mood: 12 },
            bonusXp: 2,
            bonusCoins: 1,
        },
    },
    {
        id: 'cocoa_caretaker',
        emoji: '☕',
        name: 'Người Chăm Ấm Áp',
        description: 'Chăm bền bỉ theo giờ và giữ pet luôn ổn định.',
        weights: { consistency: 0.28, nurturing: 0.24, hygiene: 0.16, affection: 0.12, discipline: 0.2 },
        skill: {
            id: 'cozy_habit',
            name: 'Thói Quen Ấm',
            description: 'Khi cho ăn hoặc tắm: +5 Health, +5 Cleanliness, +3 XP.',
            triggerActions: ['feed', 'bathe'],
            cooldownMinutes: 100,
            bonusStats: { health: 5, cleanliness: 5 },
            bonusXp: 3,
            bonusCoins: 1,
        },
    },
    {
        id: 'quartz_engineer',
        emoji: '🪨',
        name: 'Kỹ Sư Tinh Thể',
        description: 'Chơi theo chiến lược, ưu tiên tối ưu dài hạn.',
        weights: { discipline: 0.3, shopper: 0.18, hygiene: 0.12, explorer: 0.16, consistency: 0.14, balance: 0.1 },
        skill: {
            id: 'precision_routine',
            name: 'Nhịp Chuẩn Xác',
            description: 'Khi tắm hoặc chơi: +6 Health, +6 Cleanliness, +3 Coins.',
            triggerActions: ['bathe', 'play'],
            cooldownMinutes: 125,
            bonusStats: { health: 6, cleanliness: 6 },
            bonusXp: 2,
            bonusCoins: 3,
        },
    },
    {
        id: 'aurora_duet',
        emoji: '🌌',
        name: 'Song Ca Cực Quang',
        description: 'Tính cách hiếm khi cả hai duy trì nhịp chăm đều nhiều ngày.',
        requirements: { teamworkMin: 60, consistencyMin: 55 },
        weights: { teamwork: 0.32, consistency: 0.24, explorer: 0.12, affection: 0.12, balance: 0.2 },
        skill: {
            id: 'aurora_wave',
            name: 'Sóng Cực Quang',
            description: 'Mọi hành động: +4 tất cả chỉ số, +7 XP, +3 Coins.',
            triggerActions: ['feed', 'pet', 'bathe', 'play'],
            cooldownMinutes: 165,
            bonusStats: { health: 4, mood: 4, hunger: 4, cleanliness: 4 },
            bonusXp: 7,
            bonusCoins: 3,
        },
    },
    {
        id: 'cuddle_architect',
        emoji: '🧸',
        name: 'Kiến Trúc Sư Âu Yếm',
        description: 'Biến mọi tương tác thành cảm giác an toàn cho pet.',
        weights: { affection: 0.38, teamwork: 0.16, moodCare: 0.2, nurturing: 0.1, consistency: 0.16 },
        skill: {
            id: 'hug_matrix',
            name: 'Ma Trận Ôm Ấp',
            description: 'Khi vuốt ve: +14 Mood, +5 Health, +2 Coins.',
            triggerActions: ['pet'],
            cooldownMinutes: 110,
            bonusStats: { mood: 14, health: 5 },
            bonusXp: 2,
            bonusCoins: 2,
        },
    },
    {
        id: 'breeze_nomad',
        emoji: '🍃',
        name: 'Lãng Khách Gió Mềm',
        description: 'Linh hoạt, thích nhịp chơi khám phá tự nhiên.',
        weights: { explorer: 0.28, consistency: 0.18, playful: 0.18, vitality: 0.16, devotion: 0.1, balance: 0.1 },
        skill: {
            id: 'drift_step',
            name: 'Bước Trôi Êm',
            description: 'Khi chơi hoặc cho ăn: +7 Hunger, +7 Mood, +4 XP.',
            triggerActions: ['play', 'feed'],
            cooldownMinutes: 115,
            bonusStats: { hunger: 7, mood: 7 },
            bonusXp: 4,
            bonusCoins: 1,
        },
    },
    {
        id: 'prism_conductor',
        emoji: '🪄',
        name: 'Nhạc Trưởng Lăng Kính',
        description: 'Phối hợp nhiều kiểu chăm sóc để giữ pet toàn diện.',
        weights: { vitality: 0.26, balance: 0.2, consistency: 0.18, teamwork: 0.18, discipline: 0.18 },
        skill: {
            id: 'prism_tune',
            name: 'Điều Âm Cầu Vồng',
            description: 'Mọi hành động: +5 Mood, +5 Health, +3 XP.',
            triggerActions: ['feed', 'pet', 'bathe', 'play'],
            cooldownMinutes: 140,
            bonusStats: { mood: 5, health: 5 },
            bonusXp: 3,
            bonusCoins: 2,
        },
    },
    {
        id: 'pearl_strategist',
        emoji: '🐚',
        name: 'Chiến Lược Gia Ngọc Trai',
        description: 'Kiểm soát tài nguyên tốt và ít lãng phí lượt chăm.',
        weights: { discipline: 0.26, shopper: 0.22, balance: 0.16, consistency: 0.14, teamwork: 0.1, nurturing: 0.12 },
        skill: {
            id: 'reserve_plan',
            name: 'Kế Hoạch Dự Trữ',
            description: 'Khi cho ăn hoặc tắm: +3 XP, +3 Coins, +4 Cleanliness.',
            triggerActions: ['feed', 'bathe'],
            cooldownMinutes: 120,
            bonusStats: { cleanliness: 4 },
            bonusXp: 3,
            bonusCoins: 3,
        },
    },
    {
        id: 'comet_chaser',
        emoji: '☄️',
        name: 'Kẻ Đuổi Sao Chổi',
        description: 'Nhịp chơi bùng nổ, thiên về hoạt động và khám phá.',
        weights: { playful: 0.3, explorer: 0.24, vitality: 0.2, devotion: 0.14, consistency: 0.12 },
        skill: {
            id: 'comet_burst',
            name: 'Bùng Nổ Sao Chổi',
            description: 'Khi chơi: +10 Health, +6 Mood, +6 XP, +2 Coins.',
            triggerActions: ['play'],
            cooldownMinutes: 115,
            bonusStats: { health: 10, mood: 6 },
            bonusXp: 6,
            bonusCoins: 2,
        },
    },
    {
        id: 'lotus_sentinel',
        emoji: '🪷',
        name: 'Canh Gác Liên Hoa',
        description: 'Hiền hòa, bền bỉ, giữ pet sạch sẽ và ổn định.',
        weights: { consistency: 0.28, hygiene: 0.22, teamwork: 0.16, balance: 0.14, vitality: 0.2 },
        skill: {
            id: 'lotus_guard',
            name: 'Lá Chắn Liên Hoa',
            description: 'Khi tắm hoặc vuốt ve: +8 Cleanliness, +8 Mood, +3 XP.',
            triggerActions: ['bathe', 'pet'],
            cooldownMinutes: 125,
            bonusStats: { cleanliness: 8, mood: 8 },
            bonusXp: 3,
            bonusCoins: 2,
        },
    },
    {
        id: 'eclipse_legend',
        emoji: '🐉',
        name: 'Huyền Thoại Nhật Thực',
        description: 'Tính cách cực hiếm khi mọi chỉ số và hành vi đều xuất sắc.',
        requirements: { vitalityMin: 85, teamworkMin: 65, consistencyMin: 60, devotionMin: 55 },
        weights: { vitality: 0.24, teamwork: 0.2, consistency: 0.18, devotion: 0.16, balance: 0.12, explorer: 0.1 },
        skill: {
            id: 'eclipse_overdrive',
            name: 'Quá Tải Nhật Thực',
            description: 'Mọi hành động: +6 tất cả chỉ số, +10 XP, +5 Coins.',
            triggerActions: ['feed', 'pet', 'bathe', 'play'],
            cooldownMinutes: 180,
            bonusStats: { health: 6, mood: 6, hunger: 6, cleanliness: 6 },
            bonusXp: 10,
            bonusCoins: 5,
        },
    },
    {
        id: 'sakura_companion',
        emoji: '🌸',
        name: 'Bạn Đồng Hành Sakura',
        description: 'Dịu dàng, nhịp chăm có kỷ luật và giàu tình cảm.',
        weights: { consistency: 0.22, affection: 0.24, discipline: 0.18, moodCare: 0.2, teamwork: 0.16 },
        skill: {
            id: 'petal_hush',
            name: 'Cánh Hoa Ru Êm',
            description: 'Khi vuốt ve hoặc cho ăn: +9 Mood, +6 Hunger, +3 XP.',
            triggerActions: ['pet', 'feed'],
            cooldownMinutes: 105,
            bonusStats: { mood: 9, hunger: 6 },
            bonusXp: 3,
            bonusCoins: 1,
        },
    },
    {
        id: 'neon_guard',
        emoji: '🛡️',
        name: 'Vệ Binh Neon',
        description: 'Giữ pet khỏe bền, ưu tiên các hành động tăng sức mạnh nhanh.',
        weights: { vitality: 0.26, discipline: 0.18, playful: 0.18, nurturing: 0.14, consistency: 0.14, devotion: 0.1 },
        skill: {
            id: 'neon_shell',
            name: 'Khiên Neon',
            description: 'Khi chơi hoặc cho ăn: +9 Health, +4 XP, +2 Coins.',
            triggerActions: ['play', 'feed'],
            cooldownMinutes: 120,
            bonusStats: { health: 9 },
            bonusXp: 4,
            bonusCoins: 2,
        },
    },
];

module.exports = {
    PERSONALITY_LOOKBACK_DAYS,
    PET_PERSONALITY_DEFINITIONS,
};
